[project]
name = "howtofish-pycheat"
version = "0.2.0rc3"
description = "Game memory manipulation and trainer framework powered by Pymem"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dnfile>=0.18.0",
    "keyboard>=0.13.5",
    "pefile>=2023.2.7",
    "pymem>=1.14.0",
    "pythonnet>=3.1.0",
    "rich>=15.0.0",
]

[project.optional-dependencies]
dev = [
    "pyinstaller>=6.22.2",
    "pytest>=8.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/howtofish_cheat"]

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
]
